### PR TITLE
Cross-build http4s module for Scala.js

### PR DESCRIPTION
**Pull request by armanbilge**
No code changes, no added dependencies.

### CODE REVIEW

**Comment by hejfelix** [comment]
Hi Arman, thanks for your PR -- could you explain a little bit about why you want the http4s support in JS?

**Comment by armanbilge** [comment]
So we can use in the browser with:
https://github.com/http4s/http4s-dom

And in Node.js serverless lambdas with:
https://github.com/typelevel/feral/

**Comment by hejfelix** [comment]
could you give the snapshot release a whirl when it's ready on maven? We don't have much of a way to test this in real life code

**Comment by armanbilge** [comment]
I don't think anyone has "real life code" written in Scala 3 😉 is there something specific you want to test?

Thanks for merging!

**Pull request merged**
